name: future_hub_test
description: "Future Hub code test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.4
  connectivity_plus: ^6.1.0
  go_router: ^14.2.0
  dio: ^5.4.3+1
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.2
  auto_size_text: ^3.0.0
  path: ^1.9.0
  http: ^1.2.2
  material_dialogs: ^1.1.4
  lottie: ^2.7.0
  google_maps_flutter: ^2.10.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/success.json

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
